### ISSUE TITLE
Setting processTimeout gives Error code: 143

### ISSUE THREAD

**Issue by koogle** [Genymobile/genymotion-gradle-plugin#3]
Whenever I try to set the processTimeout Gradle in Android Studio refreshes with no problem but when I run the test I get:

```
A problem occurred configuring project ':app'.
> Failed to notify project evaluation listener.
   > GMTool command failed. Error code: 143.
```

My build.gradle

```
...
genymotion {
    config {
        genymotionPath = "/Applications/Genymotion.app/Contents/MacOS/"
        verbose = true
        processTimeout = 1000
        taskLaunch = "connectedAndroidTestOriginalDebug"
    }
    devices {
        Nexus5 {
            template "Google Nexus 5 - 4.4.4 - API 19 - 1080x1920"
            clearLogAfterBoot true
            stopWhenFinish true
        }
    }
}
...
```

**Comment by eyal-lezmy** [comment]
Hi @koogle,
Thanks a lot for your feedback.

The `processTimeout` you set is very small. It implies, every request done by the plugin command line (notably with gmtool) has to be less than 1 second long. Depending on your computer and the number of Genymotion devices you can easily go over that limit.

Except if you have very specific debug problems you should not change this value. We will improve the plugin output and the documentation so that this point is more clear for the users.

If you have specific needs please let us know.

**Comment by koogle** [comment]
Thanks for the reply.
So the value is set in Miliseconds? If you could just clear that up, that would be great.
We just use Genymotion to setup an android CI environment. Since the test run in the emulator on a quite old notebook, we ran into the timeout. 
I think if it was just due to the missing documentation we can close this issue.

**Comment by eyal-lezmy** [comment]
Yes that's in milliseconds. 

We will check everything is clear in the doc. 

Thanks a lot for your feedback again
